type Borrow {
  cost: Float!
  id: Int!
  loanPeriod: TimeSlot!
  status: BorrowStatus!
  timeReturned: Date
  tool: Tool!
  user: User!
}

enum BorrowStatus {
  pending
  rejected
  accepted
}

# Returns the number of seconds since January, 1st, 2001: 12:00 am, ie Date(timeIntervalSinceReferenceDate: )
scalar Date

type GeoLocation {
  lat: Float!
  lon: Float!
}

input GeoLocationInput {
  lat: Float!
  lon: Float!
}

type Mutation {
  # Adds a new tool with the given properties, and returns the integer ID of the new tool
  addTool(tool: NewToolInput!): Int!
  approveBorrow(id: Int!): Boolean!
  deleteTool(toolId: Int!): Boolean!
  denyBorrow(id: Int!): Boolean!
  requestBorrow(userId: Int!, toolId: Int!, startTime: Date!, endTime: Date!): Int!
  updateTool: Boolean!
}

input NewToolInput {
  condition: ToolCondition!
  description: String!
  location: GeoLocationInput!
  name: String!
  ownerId: Int!
}

type Query {
  borrow(id: Int!): Borrow
  nearby(radius: Float!, center: GeoLocationInput!): [Tool!]!
  self: User
  tool(id: Int!): Tool
}

type TimeSlot {
  end: Date!
  start: Date!
}

type Tool {
  # The history of this tool being loaned out
  borrowHistory: [Borrow!]!
  condition: ToolCondition!
  description: String!
  hourly_cost: Float!
  id: Int!
  images: [String!]!
  location: GeoLocation!
  name: String!
  owner: User!
  ratings: [ToolRating!]!
  schedule: [TimeSlot!]!
  tags: [String!]!
}

enum ToolCondition {
  fair
  good
  new
  great
  poor
}

type ToolRating {
  rating: Int!
  review: String
  tool: Tool!
  user: User!
}

type User {
  borrowHistory: [Borrow!]!
  email: String!
  id: Int!
  name: String!
  ownedTools: [Tool!]!
  phoneNumber: String!
  ratings: [UserRating!]!
}

type UserRating {
  rating: Int!
  review: String
  reviewee: User!
  reviewer: User!
}

