type Borrow {
  cost: Float!
  id: Int!
  loanPeriod: TimeSlot!

  # Whether or not the return was accepted by the tool owner
  returnAccepted: Boolean
  status: BorrowStatus!

  # Number of seconds since Jan 01, 2001. I.e. timeIntervalSinceReferenceDate
  timeReturned: Float
  tool: Tool!
  user: User!
}

enum BorrowStatus {
  accepted
  pending
  rejected
}

type GeoLocation {
  lat: Float!
  lon: Float!
}

input GeoLocationInput {
  lat: Float!
  lon: Float!
}

type Mutation {
  acceptReturn(borrowId: Int!, accept: Boolean!): Borrow

  # Adds a new tool with the given properties, and returns the created Tool object
  addTool(tool: NewToolInput!): Tool!
  approveBorrow(id: Int!): Boolean!
  createToolRating(revieweeId: Int!, reviewerId: Int!, review: String, rating: Int!): ToolRating!
  createUserRating(reviewerId: Int!, rating: Int!, review: String, revieweeId: Int!): UserRating!
  deleteTool(id: Int!): Boolean!
  deleteToolRating(revieweeId: Int!, reviewerId: Int!): Boolean!
  deleteUserRating(reviewerId: Int!, revieweeId: Int!): Boolean!
  denyBorrow(id: Int!): Boolean!
  requestBorrow(
    # Number of seconds since Jan 01, 2001. I.e. timeIntervalSinceReferenceDate
    startTime: Float!
    toolId: Int!
    userId: Int!

    # Number of seconds since Jan 01, 2001. I.e. timeIntervalSinceReferenceDate
    endTime: Float!
  ): Int!
  returnTool(borrowId: Int!): Borrow
}

input NewToolInput {
  condition: ToolCondition!
  description: String!
  hourlyCost: Float!
  location: GeoLocationInput!
  name: String!
  ownerId: Int!

  # Tags (ie handtool, powertool, etc). Must have at least 1
  tags: [String!]!
}

type Query {
  # Get a given borrow by id
  borrow(id: Int!): Borrow

  # Find all tools within a given radius, centered at a point
  nearby(
    center: GeoLocationInput!
    radius: Float!

    # Optional string to specify a category to filter by (ie "outdoor")
    category: String
  ): [Tool!]!
  self: User

  # Get a tool by id
  tool(id: Int!): Tool
}

type TimeSlot {
  # Number of seconds since Jan 01, 2001. I.e. timeIntervalSinceReferenceDate
  end: Float!

  # Number of seconds since Jan 01, 2001. I.e. timeIntervalSinceReferenceDate
  start: Float!
}

type Tool {
  averageRating: Float!

  # The history of this tool being loaned out
  borrowHistory: [Borrow!]!
  condition: ToolCondition!
  description: String!
  hourly_cost: Float!
  id: Int!
  images: [String!]!
  location: GeoLocation!
  name: String!
  owner: User!
  ratings: [ToolRating!]!
  schedule: [TimeSlot!]!
  tags: [String!]!
}

enum ToolCondition {
  fair
  poor
  good
  great
  new
}

type ToolRating {
  rating: Int!
  review: String
  tool: Tool!
  user: User!
}

type User {
  borrowHistory: [Borrow!]!
  email: String!
  id: Int!
  name: String!
  ownedTools: [Tool!]!
  phoneNumber: String!
  ratings: [UserRating!]!
}

type UserRating {
  rating: Int!
  review: String
  reviewee: User!
  reviewer: User!
}

